The newsweek.com clone
Abdoulaye-Thespy/TNW-clone pull request #4
Opened 2020-04-23 14:36 UTC by Abdoulaye-Thespy

In this project, I built a responsive clone of the web page of the newsweek.com.
The project is meant to be an avenue for us to practice building responsive web designs.using boostrap
It was built with html and css and boostrap.

2020-04-23 18:05 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-23 18:19 UTC, mikenath223 requested changes
Hi @Abdoulaye-Thespy  👋

This project looks awesome. You've done quite well on this.🚀

However, we are just one step away from a thumbs-up, kindly fix this issue:

- [ ] Please on **tablet screen sizes** add more left and right margin to the sections that come below the `IN THE MAGAZINE` section. 

**THIS IS YOURS**👇
![ice_screenshot_20200423-191302](https://user-images.githubusercontent.com/33323077/80134781-2c6b3200-8597-11ea-83b8-3736f0862398.png)

**THIS IS WHAT IS EXPECTED**👇
![ice_screenshot_20200423-191317](https://user-images.githubusercontent.com/33323077/80134814-38ef8a80-8597-11ea-89f9-4f85a0d3ef74.png)

Kindly fix these issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-23 22:28 UTC, men32z requested changes
Hey @Abdoulaye-Thespy !
## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### all changes are REQUIRED

#### take a look in the image, yours is the top one
![sc1](https://user-images.githubusercontent.com/9115996/80155205-ddb59c00-8586-11ea-94f0-38facffbcb5c.png)
in wide screens
- [ ] add the white background in the main section, you have currently just the gray one.
- [ ] add padding to subscribe button

#### take a look in the image, yours is the left one
![sc2](https://user-images.githubusercontent.com/9115996/80155207-de4e3280-8586-11ea-83b2-b5d9aa02e86b.png)
in small screens 
- [ ] fix the size of the navbar in small screen sizes.
- [ ] use the right font size and bold for the titles like "TOP STORY"
- [ ] make sure images don't get distorted on resizing the window.

#### take a look in the image, yours is the left one
![sc3](https://user-images.githubusercontent.com/9115996/80155210-df7f5f80-8586-11ea-845a-a905a9e5f19f.png)
- [ ] make the changes on small screens for the "the starting 5" section it changes.
- [ ] remove in small screens the "|" separators in the footer menu.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! :hammer:

--Luis Preza

## Status Request changes

2020-04-24 08:26 UTC, sumancrest0001 commented
**Good job @Abdoulaye-Thespy,** :clap:  :clap: 
You have fixed most of the issues addressed by the previous TSEs but some of them are still there. We need to fix the following issues to get approval for this project. 
**Note: All the changes are compulsory.**

We have to fix the alignment of nav items on the large screen. Let's align the subscribe button at the bottom.
Currently :point_down: 
![Screenshot from 2020-04-24 14-10-35](https://user-images.githubusercontent.com/37747619/80191457-7571c380-8635-11ea-8e52-039ac45c2105.png)

It should be :point_down: 
![Screenshot from 2020-04-24 14-10-48](https://user-images.githubusercontent.com/37747619/80191489-802c5880-8635-11ea-9ab7-a0a646e5d985.png)

2020-04-24 08:30 UTC, sumancrest0001 commented
Please fix the sign-in column on the medium screen. Currently, it is covering the whole screen but It should be centered and must not cover the whole screen. See the difference.
![Screenshot from 2020-04-24 14-01-41](https://user-images.githubusercontent.com/37747619/80191792-f3ce6580-8635-11ea-9711-bc4092875753.png)
on the actual page :point_down: 
![Screenshot from 2020-04-24 14-02-03](https://user-images.githubusercontent.com/37747619/80191804-f8931980-8635-11ea-82d4-0a4fc8537d92.png)

2020-04-24 08:32 UTC, sumancrest0001 commented
We have to fix the alignment of the title and image on a small screen. 
currently :point_down: 
![Screenshot from 2020-04-24 13-47-33](https://user-images.githubusercontent.com/37747619/80192014-4576f000-8636-11ea-8528-40e53e04d8ad.png)
it should be :point_down: :point_down: 
![Screenshot from 2020-04-24 13-48-32](https://user-images.githubusercontent.com/37747619/80192054-56bffc80-8636-11ea-83d3-8d13b04652dc.png)

2020-04-24 08:34 UTC, sumancrest0001 commented
The bottom Newsweek logo section is still not fixed for small screen devices. Please solve the alignment issue.
currently :point_down: :point_down: 
![Screenshot from 2020-04-24 13-51-20](https://user-images.githubusercontent.com/37747619/80192233-9a1a6b00-8636-11ea-97c8-14511d0bd4ea.png)

2020-04-24 08:43 UTC, sumancrest0001 commented on styles.css
> +
We can define margin and padding in one line. For example, `margin: top right bottom left`. We should follow the DRY principle [reference](https://www.w3schools.com/cssref/pr_margin.asp)
Please try to match font-size and font-weight if not font-family of the original site as it is a clone project.

2020-04-24 08:45 UTC, sumancrest0001 requested changes
Please make the above-requested changes and submit for another review.
**If you have any questions or need help, do not hesitate to contact me on slack (Suman Shrestha)**the 
All the best :+1:

2020-04-24 12:48 UTC, uryelah commented
Hello **Abdoulaye Razak**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

Great job fixing the last required changes.

------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

----

## Optional Changes (not required but will make your project more professional)

- [ ] Your footer logo has a background-color. This is not good as it looks weird if the footer background color is different, in this case, white against grey. 
Make sure you ALWAYS use svg images for logos or png images with a transparent background. 
[To learn more about svg read this article. ](https://svgontheweb.com/)
Tip, you can get the logo svg directly from the original site if you inspect it.


**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-04-25 14:35 UTC, merged